# Q3 项目配置文件
# NIPT BMI分组与最佳时点优化

# 数据配置
data:
  input_file: "data/q3_preprocessed.csv"
  threshold: 4.0                    # Y染色体浓度阈值（%）
  gestational_range: [10, 25]      # 孕周分析范围
  male_only: true                   # 仅分析男胎数据
  
  # 数据清洗参数
  outlier_method: "iqr"            # 异常值检测方法：iqr/mad/quantile
  outlier_factor: 1.5              # IQR倍数
  y_pct_upper_quantile: 99.5       # Y浓度上分位数截断
  min_observations_per_id: 1       # 每个ID最少观测次数

# 特征工程
features:
  continuous_vars: ["age", "GC", "readcount"]
  interaction_terms: 
    - ["BMI", "gest_week"]
    - ["GC", "gest_week"]
    - ["age", "BMI"]
  time_transforms:
    - "log"
    - "sqrt"
  standardize: true                # 是否标准化连续变量

# 建模配置
modeling:
  # 达标概率建模
  attain_model: 
    type: "xgboost"                # 模型类型：xgboost/quantile/gam/logistic
    params:
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.1
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42
    monotonic_constraints: 
      gest_week: 1                 # 孕周单调递增约束
  
  # 成功率建模  
  success_model:
    type: "xgboost"                # 模型类型：xgboost/logistic/gam
    params:
      n_estimators: 100
      max_depth: 4
      learning_rate: 0.1
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42
  
  # 生存分析建模
  survival_model:
    type: "aft"                    # 模型类型：aft/cox
    distributions: 
      - "weibull"
      - "lognormal" 
      - "loglogistic"
    selection_criterion: "aic"     # 模型选择标准：aic/bic/concordance

  # 交叉验证设置
  cross_validation:
    method: "group_kfold"          # 验证方法：group_kfold/leave_one_out
    n_folds: 5                     # 折数
    group_by: "ID"                 # 分组变量（避免数据泄漏）
    test_size: 0.2                 # 测试集比例
    random_state: 42

# BMI分组配置
grouping:
  method: "hybrid"                 # 分组方法：hybrid/tree/dp/custom
  
  # WHO基准切点
  who_cuts: [18.5, 25.0, 30.0]   # WHO标准BMI分界点
  
  # 决策树参数（当method包含tree时）
  tree_params:
    max_depth: 3
    min_samples_leaf: 50
    min_samples_split: 100
    random_state: 42
  
  # 动态规划参数（当method包含dp时）  
  dp_params:
    penalty_weight: 0.1            # 切点数量惩罚权重
    max_cuts: 5                    # 最大切点数量
  
  # 约束条件
  constraints:
    min_group_size: 50             # 最小组内样本量
    min_cut_distance: 2.0          # 最小切点间距（kg/m²）
    max_groups: 6                  # 最大分组数量
  
  # 微调参数  
  fine_tuning:
    delta: 2.0                     # WHO切点微调窗口（±delta）
    search_method: "tree"          # 微调搜索方法：tree/dp/grid

# 优化配置
optimization:
  # 时间网格
  time_grid:
    start: 10.0                    # 起始孕周
    end: 25.0                      # 结束孕周
    step: 0.25                     # 网格步长（周）
    fine_step: 0.05                # 精细搜索步长（周）
  
  # 约束条件
  constraints:
    min_success_prob: 0.8          # 最小可接受检测成功概率
    max_time: 25.0                 # 最大允许检测时间
  
  # 风险函数权重
  risk_weights:
    time_weights: [1.0, 3.0, 8.0] # 早中晚期时间惩罚权重
    failure_cost: 5.0              # 失败重检代价系数
    delay_penalty: 1.5             # 延迟惩罚系数
  
  # 重检策略优化（可选）
  retest_strategy:
    enabled: true                  # 是否启用重检策略优化
    max_delay: 3.0                 # 最大重检延迟（周）
    delay_options: [1.0, 1.5, 2.0] # 重检延迟选项（周）

# 敏感性分析配置
sensitivity:
  # 阈值敏感性
  threshold_sensitivity:
    enabled: true
    threshold_range: [3.5, 4.0, 4.5] # 阈值测试范围（%）
  
  # 误差敏感性
  error_sensitivity:
    enabled: true
    error_multipliers: [0.8, 1.0, 1.2] # 误差倍数扰动
  
  # 权重敏感性  
  weight_sensitivity:
    enabled: true
    time_weight_scenarios:
      - [0.5, 2.0, 5.0]           # 保守场景
      - [1.0, 3.0, 8.0]           # 基线场景  
      - [2.0, 5.0, 12.0]          # 激进场景
    failure_cost_range: [3.0, 5.0, 8.0]
  
  # Bootstrap设置
  bootstrap:
    enabled: true
    n_samples: 500                 # Bootstrap样本数
    confidence_level: 0.95         # 置信水平
    random_state: 42

# 验证配置
validation:
  # 内部验证
  internal_validation:
    enabled: true
    cv_repeats: 3                  # 交叉验证重复次数
    
  # 时间外推验证
  temporal_validation:
    enabled: true
    train_range: [10, 20]          # 训练数据时间范围
    test_range: [20, 25]           # 测试数据时间范围
  
  # 评估指标
  metrics:
    - "auc"                        # ROC曲线下面积
    - "brier_score"                # Brier分数  
    - "calibration"                # 校准曲线
    - "concordance"                # C指数（生存分析）

# 输出配置
output:
  base_dir: "outputs"              # 输出基目录
  
  # 主要输出文件
  main_outputs:
    bmi_groups: "bmi_groups_optimal.csv"
    wstar_curve: "wstar_curve.csv" 
    sensitivity_threshold: "threshold_sensitivity.csv"
    sensitivity_error: "error_sensitivity.csv"
    model_performance: "model_performance.csv"
    
  # 图表输出
  figures:
    enabled: true
    format: "png"                  # 图片格式：png/pdf/svg
    dpi: 300                       # 图片分辨率
    style: "seaborn-v0_8"         # 绘图样式
    
    plots:
      wstar_curve: "wstar_curve.png"
      group_recommendations: "group_recommendations.png" 
      sensitivity_heatmap: "sensitivity_heatmap.png"
      survival_curves: "survival_curves.png"
      calibration_plots: "calibration_plots.png"
  
  # 报告生成
  reports:
    enabled: true
    format: ["txt", "html"]        # 报告格式
    include_config: true           # 是否包含配置信息
    include_diagnostics: true      # 是否包含诊断信息

# 计算资源配置
computing:
  # 并行计算
  parallel:
    enabled: true
    n_jobs: -1                     # 并行作业数（-1为全部CPU）
    backend: "loky"                # 并行后端：loky/threading/multiprocessing
  
  # 内存管理
  memory:
    chunk_size: 10000              # 数据处理块大小
    low_memory: false              # 低内存模式
  
  # 随机种子
  random_state: 42               # 全局随机种子

# 日志配置
logging:
  level: "INFO"                    # 日志级别：DEBUG/INFO/WARNING/ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "outputs/logs/analysis.log" # 日志文件路径
  console: true                    # 是否输出到控制台

# 调试配置
debug:
  enabled: false                   # 是否启用调试模式
  save_intermediate: false         # 是否保存中间结果
  plot_diagnostics: true           # 是否绘制诊断图
  verbose_progress: true           # 是否显示详细进度

# 元数据
metadata:
  project_name: "Q3_NIPT_BMI_Optimization"
  version: "1.0.0"
  author: "Q3 Project Team"
  created_date: "2024-01-01"
  description: "NIPT最佳检测时点的BMI分组优化分析"